### ISSUE TITLE
"Non-negative number required" at GameTableManager.cs

### ISSUE THREAD

**Issue by dalss-iscteiulpt** [NexusForever/NexusForever#12]
![image](https://user-images.githubusercontent.com/25645939/48581911-0c076480-e91b-11e8-8d82-72fc1aa21768.png)

I keep screwing this up and I have no idea why, any tips?

Basically it happens when loading the .tbl's. They all are at NexusForever-master\Source\NexusForever.WorldServer\bin\Debug\netcoreapp2.1\tbl\ by the way.

**Comment by Rawaho** [comment]
A few people have mentioned this issue, it's due to the tbl extraction failing and resulting in "garbage" contents or no contents at all.
If extracting the tbl files again doesn't yield a better result you can contact me on Discord (see profile) and I will send you the full set of valid tbl files.
The correct fix for this issue is to implement our own extractor, I have yet to start work on this.

**Comment by dalss-iscteiulpt** [comment]
Thanks mate that worked.
