### ISSUE TITLE
[Travis] Release Builds for MapGenerator and ClientConnector

### ISSUE THREAD

**Issue by Vortelf** [NexusForever/NexusForever#282]
Hello,

So I've setup everything using the zips from Releases but I found out I need to compile two more projects to actually test it, which was a bummer.

Could you add to MapGenerator, ClientConnector and the new Database to Travis? If there  isn't something special about building them, it would be a simple copy/paste. Way simpler than everyone who want to try it needing to setup .NET SDK for building and so on.

**Comment by kardall** [comment]
Well the MapGenerator is absolutely needed for the WorldServer. It creates the tbl files needed for it to function.

ClientConnector makes it so you can connect to your server with the game client.

If you cloned the master or develop branch, you should have these in your solution anyway though, and building the solution should do everything for you. Then you have to actually run the MapGenerator to get your Tbl files for the WorldServer.

**Comment by Vortelf** [comment]
I don't think you get what I was saying, @kardall. I don't want to spend the time to setup Visual Studio, environment, etc and build the whole project while it could be automated with the already existing Travis CI on every merged pull request or via tags and create a new release.

**Comment by kardall** [comment]
If you need a pre-compiled version of the MapGenerator and ClientConnector that can be arranged. Those ones are included in the solution but are not required for the server itself to run, only the files that the MapGenerator creates. And they are above 2.6gb in size when done :)

Most people don't like pre-compiling simply because someone may edit the code and put in things in that are not intended/official. That's why compiling yourself from the source is the safest option :)

I am curious though, if you have pre-compiled zips of the world server, auth server, sts server already, I find it curious that the source of these archives do not make the other two available :/ hmm... very strange.

**Comment by Rawaho** [comment]
New releases now include client tools.
