### ISSUE TITLE
NuGet package installation for dummies (without VS)

### ISSUE THREAD

**Issue by codemasher** [NexusForever/NexusForever#77]
Hey! First of all thank you for that nice christmas present!
In order to get it running, is there an easy way to install the NuGet dependencies without Visual Studio? I see there's a [command line tool](https://www.nuget.org/downloads) but i have no clue how to make it install the packages (am i right assuming the `NexusForever.*.deps.json` are the packages to install?).
An additional line or two in the readme would be great!

**Comment by Fabi** [comment]
the `dotnet build` command auto restores everything

**Comment by codemasher** [comment]
I'm not building from the source, i'm checking out [the compiled release files](https://github.com/NexusForever/NexusForever/releases/tag/Travis-a6bc30b7945af059a68865b0eb2dbebf88750b0e) and there's no `.sln` to build from, but i somehow need the dependencies. (Win7 btw.)

**Comment by Fabi** [comment]
these should already include all dependencies since the repo is using dotnet publish. If not, there are some configuration issues.

**Comment by codemasher** [comment]
Hope this helps:

Auth & Sts:
```
Error:
  An assembly specified in the application dependencies manifest (NexusForever.AuthServer.deps.json) was not found:
    package: 'Microsoft.EntityFrameworkCore.Abstractions', version: '2.1.4'
    path: 'lib/netstandard2.0/Microsoft.EntityFrameworkCore.Abstractions.dll'
```
World:
```
Error:
  An assembly specified in the application dependencies manifest (NexusForever.WorldServer.deps.json) was not found:
    package: 'MessagePack', version: '1.7.3.4'
    path: 'lib/netstandard2.0/MessagePack.dll'
```

**Comment by jasoncouture** [comment]
What command are you using to launch the server?

**Comment by Fabi** [comment]
The pre compiled binaries don't seem to include all deps. That's the problem.

**Comment by jasoncouture** [comment]
The pre-compiled binaries do not include the deps, and as far as I know there is no simple way to get them from deps.json files.
PR #78 aims to fix this, by adding all of the published files, instead of attempting to keep the zip small. #78 will allow the servers to run without any .NET framework installed on the host machine, provided other requirements are met. (For linux, this requires the following to be installed on the host: liblttng-ust0, libcurl4, libssl1.0.0, libkrb5-3, zlib1g, for windows it should "Just work")
